import type { Metadata } from "next";
import { SITE_NAME, absoluteUrl } from "./site";

/**
 * Absolute URL of the site-wide Open Graph image (generated by the
 * file-based src/app/opengraph-image.tsx route at /opengraph-image).
 *
 * This MUST be passed explicitly below: when a page sets its own
 * `openGraph` object, Next.js stops auto-injecting the file-convention
 * OG image — so without this every buildPageMetadata page would ship a
 * social card with no image. (1200×630, matching the route's `size`.)
 */
const OG_IMAGE = {
  url: absoluteUrl("/opengraph-image"),
  width: 1200,
  height: 630,
  alt: SITE_NAME,
};

interface PageMetadataInput {
  title: string;
  description: string;
  path: string; // e.g. "/about" — leading slash required
  /** Optional override for OG title/description */
  ogTitle?: string;
  ogDescription?: string;
}

/**
 * Build per-page Metadata that includes canonical URL, Open Graph, and
 * Twitter Card tags consistent with the site defaults.
 *
 * The site's metadataBase (set in root layout) resolves the canonical to
 * an absolute URL; we still pass a leading-slash path here so it's explicit.
 */
export function buildPageMetadata({
  title,
  description,
  path,
  ogTitle,
  ogDescription,
}: PageMetadataInput): Metadata {
  const fullTitle = `${title} | ${SITE_NAME}`;
  const og = ogTitle || fullTitle;
  const ogDesc = ogDescription || description;

  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      url: path,
      title: og,
      description: ogDesc,
      siteName: SITE_NAME,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: og,
      description: ogDesc,
      images: [OG_IMAGE.url],
    },
  };
}
